server:
  port: ${SERVER_PORT:8080}
  host: 0.0.0.0

app:
  greeting: "Hello"

db:
  source: "mongoDb"

  connection:
    #url: "mongodb://127.0.0.1:27017/pokemon"
    url: ${MONGODB_URI}

  init-schema: false
  init-data: true

  health-check:
    type: "query"
    statementName: "health-check"

  statements:

    health-check: |
      {
        "operation": "command",
        "query": {
          "ping": 1
        }
      }

    insert-type: |
      {
        "collection": "types",
        "value": {
          "_id": ?,
          "name": ?
        }
      }

    insert-pokemon: |
      {
        "collection": "pokemons",
        "value": {
          "_id": ?,
          "name": ?,
          "idType": ?
        }
      }

    select-all-types: |
      {
        "collection": "types",
        "query": {}
      }

    select-all-pokemons: |
      {
        "collection": "pokemons",
        "query": {}
      }

    select-pokemon-by-id: |
      {
        "collection": "pokemons",
        "query": {
          "_id": $id
        }
      }

    select-pokemon-by-name: |
      {
        "collection": "pokemons",
        "query": {
          "name": ?
        }
      }

    update-pokemon-by-id: |
      {
        "collection": "pokemons",
        "query": {
          "_id": $id
        },
        "value": {
          "$set": {
            "name": $name,
            "idType": $type
          }
        }
      }

    delete-pokemon-by-id: |
      {
        "collection": "pokemons",
        "query": {
          "_id": $id
        }
      }

    delete-all-pokemons: |
      {
        "collection": "pokemons",
        "query": {}
      }

    delete-all-types: |
      {
        "collection": "types",
        "query": {}
      }